#!/usr/bin/bash

root="/c/Users/kalle.tolonen/ratko"
be="ratko-backend"
ui_be="ratko-ui-backend"
fe="ratko-frontend"
this_directory=$pwd

cd $root/$be
branch=$(git branch --show-current)
echo -e "Updating $be (branch: \033[32m$branch\033[0m)"
git pull

cd $root/$ui_be
branch=$(git branch --show-current)
echo -e "Updating $ui_be (branch: \033[32m$branch\033[0m)"
git pull

cd $root/$fe
branch=$(git branch --show-current)
echo -e "Updating $fe (branch: \033[32m$branch\033[0m)"
git pull

cd $this_directory


