#!/usr/bin/bash
#version=5
root="/c/Users/kalle.tolonen/ratko"
be="ratko-backend"
ui_be="ratko-ui-backend"
fe="ratko-frontend"
this_directory=$(pwd)
declare -a branch_names

update_and_record_branch() {
  local component=$1
  cd "$root/$component"
  local branch=$(git branch --show-current)
  branch_names+=("$component: $branch")
  echo -e "Updating \033[44m$component\033[0m"
  git pull
}

update_and_record_branch "$be"
update_and_record_branch "$ui_be"
update_and_record_branch "$fe"

echo -e
echo -e "Current branch:"
for branch in "${branch_names[@]}"; do
  component=$(echo $branch | cut -d ':' -f 1)
  branch_name=$(echo $branch | cut -d ':' -f 2)
  
  echo -e "$component: \033[32m$branch_name\033[0m"
done

cd "$this_directory"