#!/usr/bin/bash


if [ -d "ratko-backend" ]; then
  cd /c/Users/kalle.tolonen/ratko/ratko-backend
  branch=$(git branch --show-current)
  echo -e "Updating ratko-backend (branch: \033[32m$branch\033[0m)"
  git pull
  cd ..
else
  echo "ratko-backend directory not found"
fi

if [ -d "ratko-ui-backend" ]; then
  cd /c/Users/kalle.tolonen/ratko/ratko-ui-backend
  branch=$(git branch --show-current)
  echo -e "Updating ratko-ui-backend (branch: \033[32m$branch\033[0m)"
  git pull
  cd ..
else
  echo "ratko-ui-backend directory not found"
fi

if [ -d "ratko-frontend" ]; then
  cd /c/Users/kalle.tolonen/ratko/ratko-frontend
  branch=$(git branch --show-current)
  echo -e "Updating ratko-frontend (branch: \033[32m$branch\033[0m)"
  git pull
  cd ..
else
  echo "ratko-frontend directory not found"
fi



